default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: adventur_dev
  username: adventur_app_user
  password: adventur

test:
  <<: *default
  database: adventur_test

production:
  <<: *default
  database: adventur
  username: adventur_app_user
